version: "3.8"
services:
  backend:
    container_name: backend
    image: app-backend
    #build: backend/.
    networks:
      - app-network
    volumes:
    - /var/lib/jenkins/workspace/pipeline/Docker/backend:/app
  frontend:
    container_name: frontend
    image: app-frontend
    #build: frontend/.
    ports:
      - "80:80"
    networks:
      - app-network
    volumes:
    - /var/lib/jenkins/workspace/pipeline/Docker/frontend:/usr/share/nginx/html
    depends_on:
      - backend
networks:
  app-network:
    driver: bridge
